### PR TITLE
[prober] delete rid-related tests from prober

### LINKED ISSUE #744: [rid-prober] migrate prober logic entirely to uss_qualifier scenarios, then remove prober
We (progressively) want to retire the current prober entirely.

Before doing so, we need to ensure that everything it tests is also being tested by uss_qualifier scenarios.

We will do so step-wise, starting with the part of the prober that tests the remote ID part of the standards.

# Gap Analysis 

The following gap analysis is based on both the older [InterUSS Backlog](https://docs.google.com/spreadsheets/d/1z-03-nBj1812xI-IkShWjY6-p7sOghSCfYapQLXenh0/edit?gid=558659655#gid=558659655) as well as a manual check of the prober files and their corresponding qualifier scenarios for RID.

In summary, the qualifier covers at least what the prober is covering with respect to both Remote ID standards v1 and v2.

| prober file | qualifier scenarios | comments | migrated |
| -------- | ----- | --- | --- |
| v1/test_isa_expiry.py | ISAExpiry | | ✅ |
| v2/test_isa_expiry.py | ISAExpiry | | ✅ |
| v1/test_isa_simple.py | ISASimple | | ✅ |
| v2/test_isa_simple.py | ISASimple | | ✅ |
| v1/test_isa_simple_heavy_traffic_concurrent.py | HeavyTrafficConcurrent | qualifier covers both v1+v2 | ✅ |
| v1/test_isa_validation.py | ISAValidation | | ✅ |
| v2/test_isa_validation.py | ISAValidation | | ✅ |
| v1/test_subscription_isa_interactions.py | ISASubscriptionInteractions | | ✅ |
| v2/test_subscription_isa_interactions.py | ISASubscriptionInteractions | | ✅ |
| v1/test_subscription_isa_slightly_overlapping.py | ISASubscriptionInteractions | qualifier scenario covers both v1+v2, and checks for subscriptions slightly overlapping the ISA | ✅ |
| v1/test_subscription_simple.py | SubscriptionSimple | | ✅ |
| v2/test_subscription_simple.py | SubscriptionSimple | | ✅ |
| v1/test_subscription_validation.py | SubscriptionValidation | | ✅ |
| v2/test_subscription_validation.py | SubscriptionValidation | | ✅ |
| v1/test_token_validation.py | TokenValidation | | ✅ |
| v2/test_token_validation.py | TokenValidation | | ✅ |

It should be noted that until https://github.com/interuss/dss/pull/1045 is merged on the DSS repo, the DSS CI will not be running the qualifier as part of the automated tests.

https://github.com/interuss/dss/pull/1066 adds mentions and pointers to the qualifier to the DSS doc

### PR DESCRIPTION
**Pull request by Shastick**
Remove the RID parts of the `prober`, which are now entirely covered by the qualifier.

Closes #744

### CODE REVIEW

**Comment by Shastick** [comment]
> @Shastick could you please check references to the prober in the dss repo documentation and make sure we properly update it in order to maintain the same level of testing by documenting the uss qualifier usage? Example: https://github.com/interuss/dss/blob/master/build/pooling.md#establishing-a-pool-with-first-instance

I did a first pass on the DSS repo (see https://github.com/interuss/dss/pull/1066): I essentially mentioned the qualifier wherever the prober was being mentioned.

**Comment by mickmis** [comment]
Could you tell me how you ensured that all of those prober tests are now covered by USS qualifier scenarios? I do see that all of those tests seem to have a matching scenario, but then did you make a pass to ensure that all test cases are covered? Thanks!

**Comment by Shastick** [comment]
> Could you tell me how you ensured that all of those prober tests are now covered by USS qualifier scenarios? I do see that all of those tests seem to have a matching scenario, but then did you make a pass to ensure that all test cases are covered? Thanks!

See #744 for the details.

**Review by mickmis — COMMENTED** [review]
Change LGTM, but shouldn't we wait for the dss repo to use the uss_qualifier for probing instead of the prober before merging?
Because in the meantime if we need to change something in the prober for the CI in the DSS, we will have an issue.

**Comment by Shastick** [comment]
Yes, I'd wait before merging this. We also still need a release of the monitoring repo in order to be able to use the qualifier.

**Comment by Shastick** [comment]
https://github.com/interuss/dss/pull/1045 has landed. @mickmis we should have proper coverage on the DSS repo without the prober as of this moment and this PR can be merged.

**Review by mickmis — APPROVED** [review]
LGTM
~~Branch needs to be updated though. @Shastick can I just update the branch through github or will you take care of it?~~ Actually not really needed, my bad.

**Pull request merged**
